name: Build APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      PATH: /usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/platform-tools:/usr/local/lib/android/sdk/emulator:/usr/local/lib/android/sdk/tools/bin:${{ env.PATH }}

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Verificar Android SDK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          echo "ANDROID_SDK_ROOT=$ANDROID_SDK_ROOT"
          which sdkmanager
          sdkmanager --version

      - name: Instalar componentes Android
        run: |
          yes | sdkmanager --licenses || true
          sdkmanager "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Dar permissão ao Gradle
        run: chmod +x android/gradlew

      - name: Compilar APK
        working-directory: android
        run: ./gradlew assembleDebug

      - name: Salvar APK
        uses: actions/upload-artifact@v4
        with:
          name: SurvivalWorld-debug
          path: android/app/build/outputs/apk/debug/app-debug.apk
